import { useState } from 'react';
import { supabase } from '../supabaseClient';

interface Center {
  id: string;
  name: string;
  location: string;
}

interface CenterFormProps {
  centerToEdit?: Center | null;
  onSuccess: () => void;
}

interface FormData {
  name: string;
  location: string;
}

export default function CenterForm({ centerToEdit = null, onSuccess }: CenterFormProps) {
  const [formData, setFormData] = useState<FormData>({
    name: centerToEdit?.name || '',
    location: centerToEdit?.location || ''
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.name || !formData.location) {
      alert("❗ Both name and location are required.");
      return;
    }

    try {
      if (centerToEdit) {
        // 🔁 Update existing center
        const { error } = await supabase.from('centers')
          .update(({
            name: formData.name,
            location: formData.location
          } as any) as never)
          .eq('id', centerToEdit.id);

        if (error) throw error;

        alert("✅ Center updated successfully.");

      } else {
        // ➕ Insert new center with auto-generated UUID
        const { error } = await supabase.from('centers')
          .insert([{
            name: formData.name,
            location: formData.location
            // id is auto-generated by Supabase UUID column default
          }] as any);

        if (error) throw error;

        alert("✅ New center created.");
      }

      onSuccess(); // reload parent or close modal

    } catch (err) {
      console.error("❌ Error saving center:", err);
      alert("An error occurred while saving the center.");
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      
      {/* Name */}
      <label>Center Name</label><br />
      <input 
        type="text"
        name="name"
        value={formData.name}
        onChange={handleChange}
        placeholder="ABO Plasma – Cherry Hill"
      /><br />

      {/* Location */}
      <label>Location / Address</label><br />
      <textarea 
        rows={3}
        name="location"
        value={formData.location}
        onChange={handleChange}
        placeholder="500 NJ-38 W, Cherry Hill, NJ 08002"
      ></textarea><br />

      {/* Submit Button */}
      <button type="submit" style={{ marginTop:'1rem' }}>
        {centerToEdit ? "💾 Update Center" : "➕ Add Center"}
      </button>

    </form>
  );
}

