import React, { useState } from 'react';
import { supabase } from '../supabaseClient';

export default function CenterForm({ centerToEdit = null, onSuccess }) {
  const [formData, setFormData] = useState({
    name: centerToEdit?.name || '',
    location: centerToEdit?.location || ''
  });

  const handleChange = (e) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.name || !formData.location) {
      alert("❗ Both name and location are required.");
      return;
    }

    try {
      if (centerToEdit) {
        // 🔁 Update existing center
        const { error } = await supabase.from('centers')
          .update({
            name: formData.name,
            location: formData.location
          })
          .eq('id', centerToEdit.id);

        if (error) throw error;

        alert("✅ Center updated successfully.");

      } else {
        // ➕ Insert new center with auto-generated UUID
        const { error } = await supabase.from('centers')
          .insert([{
            name: formData.name,
            location: formData.location
            // id is auto-generated by Supabase UUID column default
          }]);

        if (error) throw error;

        alert("✅ New center created.");
      }

      onSuccess(); // reload parent or close modal

    } catch (err) {
      console.error("❌ Error saving center:", err.message);
      alert("An error occurred while saving the center.");
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      
      {/* Name */}
      <label>Center Name</label><br />
      <input 
        type="text"
        name="name"
        value={formData.name}
        onChange={handleChange}
        placeholder="ABO Plasma – Cherry Hill"
      /><br />

      {/* Location */}
      <label>Location / Address</label><br />
      <textarea 
        rows="3"
        name="location"
        value={formData.location}
        onChange={handleChange}
        placeholder="500 NJ-38 W, Cherry Hill, NJ 08002"
      ></textarea><br />

      {/* Submit Button */}
      <button type="submit" style={{ marginTop:'1rem' }}>
       {centerToEdit ? "💾 Update Center" : "➕ Add Center"}
     </button>

   </form>
 );
}